### ISSUE TITLE
Don't do openapi validations on VMs

### ISSUE THREAD

**Issue by rmohr** [fromanirh/kubevirt-template-validator#12]
kubevirt already does openapi validation. Please only do your additional validations on top of that.

This https://github.com/fromanirh/kubevirt-template-validator/blob/896dbce0ae70f6a518d99293473f39258c8814be/pkg/webhooks/utils.go#L36 should not be used.

**Comment by fromanirh** [comment]
ack, let's remove this.

**Comment by fromanirh** [comment]
https://github.com/fromanirh/kubevirt-template-validator/pull/14
